C Declarations for DUNGEON
C
C COPYRIGHT 1980, 1990, INFOCOM COMPUTERS AND COMMUNICATIONS, CAMBRIDGE MA.
C ALL RIGHTS RESERVED, COMMERCIAL USAGE STRICTLY PROHIBITED
C WRITTEN BY R. M. SUPNIK
C
C This file should be included in *all* modules to supply consistent
C data structure definitions.
C
C 02-Dec-15     EMG     Update to compile using gfortran      
C 29-Sep-94      RMS      Added COUNT, LDOOR, HEADS, COKES, GBROCH, SHOUS,
C                  FORE2, DIGBT.  Deleted SLEPBT.  Modified GLOBAL.
C 01-Feb-94      RMS      Aligned vocabulary COMMON.
C 25-Jan-94      RMS      Added sandy beach room.







      INTEGER SYN(11)
      EQUIVALENCE (SYN(1),VFLAG)

C
C Screen of light state

      integer FROMDR,SCOLRM,SCOLAC,SCOLDR(8),SCOLWL(12)
      COMMON /SCREEN/ FROMDR,SCOLRM,SCOLAC, SCOLDR,SCOLWL
C
C Puzzle room state
      integer CPDR(16),CPWL(8),CPVEC(64)
      COMMON /PUZZLE/ CPDR,CPWL,CPVEC
C
C Message index
      integer MLNT,RTEXT(MMAX)
      COMMON /RMSG/ MLNT,RTEXT


C
C Exits

      integer XLNT,TRAVEL(XXMAX)
      COMMON /EXITS/ XLNT,TRAVEL

      integer XELNT(4),XTYPE,XROOM1,XSTRNG,XACTIO,XOBJ,xflag
      COMMON /CURXT/ XELNT,XTYPE,XROOM1,XSTRNG,XACTIO,XOBJ
      EQUIVALENCE (XFLAG,XOBJ)

C
C Villains and demons
C
      LOGICAL THFFLG,SWDACT,THFACT
      integer THFPOS,SWDSTA
      COMMON /HACK/ THFPOS,THFFLG,THFACT,SWDACT,SWDSTA

      integer VLNT,VILLNS(VMAX),VPROB(VMAX),VOPPS(VMAX),
     &      VBEST(VMAX),VMELEE(VMAX)
      COMMON /VILL/ VLNT,VILLNS,VPROB,VOPPS, VBEST,VMELEE

C
C Flags
C
      LOGICAL FLAGS(FMAX)
      EQUIVALENCE (FLAGS(1),TROLLF)
      INTEGER SWITCH(SMAX)
      EQUIVALENCE (SWITCH(1),BTIEF)


      integer  BTIEF,BINFF,RVMNT,RVCLR,RVCYC,RVSND,RVGUA,
     & ORRUG,ORCAND,ORMTCH,ORLAMP, MDIR,MLOC,POLEUF,
     & QUESNO,NQATT,CORRCT, lcell,PNUMB,ACELL,DCELL,CPHERE,TTIE,MATOBJ
      COMMON /FINDEX/ BTIEF,BINFF
      COMMON /FINDEX/ RVMNT,RVCLR,RVCYC,RVSND,RVGUA
      COMMON /FINDEX/ ORRUG,ORCAND,ORMTCH,ORLAMP
      COMMON /FINDEX/ MDIR,MLOC,POLEUF
      COMMON /FINDEX/ QUESNO,NQATT,CORRCT
      COMMON /FINDEX/ LCELL,PNUMB,ACELL,DCELL,CPHERE
      COMMON /FINDEX/ TTIE,MATOBJ
